project:
  type: default

author: "[hachiman_oct](https://github.com/hachiman-oct)"
date: today
format:
  html:
    toc: true
    toc_float: false
    toc-depth: 5
    toc-expand: 2
css:  
  - https://cdn.jsdelivr.net/gh/hachiman-oct/resources@main/qmd/darkmode.css
  #- https://cdn.jsdelivr.net/gh/hachiman-oct/resources@main/qmd/toc-right-toggle.css
  - test_resources/toc-right-toggle.css